/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.romanrum45.view;

import com.romanrum45.controller.SelectionControllerInterface;
import com.romanrum45.model.AdvertOfCarsModelInterface;
import com.romanrum45.observers.AdvertsObserver;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rum
 */
public class SelectionGUI extends JFrame implements AdvertsObserver {

    private SelectionControllerInterface controller;
    private AdvertOfCarsModelInterface model;

    /**
     * Creates new form NewJFrame
     *
     * @param controller
     * @param model
     */
    public SelectionGUI(SelectionControllerInterface controller, AdvertOfCarsModelInterface model) {

        this.controller = controller;
        this.model = model;
        model.registerObserver(SelectionGUI.this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxBrands = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxModels = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMinPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMaxPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBtnSubmit = new javax.swing.JButton();
        jBtnStopSubmit = new javax.swing.JButton();
        jBtnSelectCity = new javax.swing.JButton();
        jTextFieldMinYear = new javax.swing.JTextField();
        jTextFieldMaxYear = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAutoList = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jTextViewCity = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Парсер");

        jLabel1.setText("Фирма:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxModels, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jLabel1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jComboBoxBrands.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Любая фирма" }));
        jComboBoxBrands.setToolTipText("");
        jComboBoxBrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBrandsActionPerformed(evt);
            }
        });

        jLabel2.setText("Модель:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jComboBoxModels, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jLabel2, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jComboBoxModels.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Любая модель" }));
        jComboBoxModels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModelsActionPerformed(evt);
            }
        });

        jLabel3.setText("Цена(руб):");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextFieldMaxYear, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jLabel3, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel4.setText("—");

        jLabel5.setText("Год:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextFieldMinYear, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jLabel5, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel6.setText("—");

        jLabel8.setText("Город:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jBtnSelectCity, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jLabel8, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jBtnSubmit.setText("Начать поиск");
        jBtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitActionPerformed(evt);
            }
        });

        jBtnStopSubmit.setText("Приостановить");
        jBtnStopSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStopSubmitActionPerformed(evt);
            }
        });

        jBtnSelectCity.setText("Выбрать");
        jBtnSelectCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelectCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnSelectCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxBrands, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnStopSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxModels, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldMinYear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMaxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBrands, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxModels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMinPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldMaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSelectCity)
                    .addComponent(jTextFieldMinYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jBtnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnStopSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jAutoList);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Drom.ru");

        jTextViewCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextViewCity.setText("Город не выбран");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(252, 252, 252)
                .addComponent(jTextViewCity)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextViewCity))
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitActionPerformed

        if (controller.getIndexCitySelected() > -1) {

            StringBuilder builderParamUrl = new StringBuilder();
            String minPrice = "&minprice=" + jTextFieldMinPrice.getText();
            String maxPrice = "&maxprice=" + jTextFieldMaxPrice.getText();
            String minYear = "&minyear=" + jTextFieldMinYear.getText();
            String maxYear = "&maxyear=" + jTextFieldMaxYear.getText();

            builderParamUrl.append("?");
            if (!jTextFieldMinPrice.getText().equals("")) {
                builderParamUrl.append(minPrice);
            }
            if (!jTextFieldMaxPrice.getText().equals("")) {
                builderParamUrl.append(maxPrice);
            }
            if (!jTextFieldMinYear.getText().equals("")) {
                builderParamUrl.append(minYear);
            }
            if (!jTextFieldMaxYear.getText().equals("")) {
                builderParamUrl.append(maxYear);
            }

            builderParamUrl.append("&go_search=2");
            controller.setBtnSubmit(builderParamUrl.toString());
        } else {
            JOptionPane.showMessageDialog(this, "Выберите город");
        }

    }//GEN-LAST:event_jBtnSubmitActionPerformed

    private void jBtnSelectCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelectCityActionPerformed

        controller.setSelectDialogCity();

    }//GEN-LAST:event_jBtnSelectCityActionPerformed

    private void jComboBoxBrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBrandsActionPerformed
        int indexBrand = jComboBoxBrands.getSelectedIndex();
        controller.setIndexBrand(indexBrand);

    }//GEN-LAST:event_jComboBoxBrandsActionPerformed

    private void jComboBoxModelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModelsActionPerformed
        int indexModel = jComboBoxModels.getSelectedIndex();
        controller.setIndexModel(indexModel);
    }//GEN-LAST:event_jComboBoxModelsActionPerformed

    private void jBtnStopSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStopSubmitActionPerformed
        controller.setBtnStopSubmit();
    }//GEN-LAST:event_jBtnStopSubmitActionPerformed

    public void createSelectionGUI() {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();
        setVisible(true);

    }

    public void enableBtnSubmit() {
        jBtnSubmit.setEnabled(true);
    }

    public void enableBtnStopSubmit() {
        jBtnStopSubmit.setEnabled(true);
    }

    public void enableBtnSelectCity() {
        jBtnSelectCity.setEnabled(true);
    }

    public void enabledComboBoxBrands() {
        jComboBoxBrands.setEnabled(true);
    }

    public void enabledComboBoxModels() {
        jComboBoxModels.setEnabled(true);
    }

    public void enabledTextFieldMinPrice() {
        jTextFieldMinPrice.setEnabled(true);
    }

    public void enabledTextFieldMaxPrice() {
        jTextFieldMaxPrice.setEnabled(true);
    }

    public void enabledTextFieldMinYear() {
        jTextFieldMinYear.setEnabled(true);
    }

    public void enabledTextFieldMaxYear() {
        jTextFieldMaxYear.setEnabled(true);
    }

    public void disabledTextFieldMaxYear() {
        jTextFieldMaxYear.setEnabled(false);
    }

    public void disabledTextFieldMinYear() {
        jTextFieldMinYear.setEnabled(false);
    }

    public void disabledTextFieldMaxPrice() {
        jTextFieldMaxPrice.setEnabled(false);
    }

    public void disabledTextFieldMinPrice() {
        jTextFieldMinPrice.setEnabled(false);
    }

    public void disabledComboBoxModels() {
        jComboBoxModels.setEnabled(false);
    }

    public void disabledComboBoxBrands() {
        jComboBoxBrands.setEnabled(false);
    }

    public void disabledBtnSelectCity() {
        jBtnSelectCity.setEnabled(false);
    }

    public void disableBtnSubmit() {
        jBtnSubmit.setEnabled(false);
    }

    public void disableBtnStopSubmit() {
        jBtnStopSubmit.setEnabled(false);
    }

    @Override
    public void updateCitySelected() {
        jTextViewCity.setText(model.getCitySelected());
    }

    @Override
    public void updateBrands() {
        String[] arrayBrands = model.getArrayBrands();
        jComboBoxBrands.setModel(new DefaultComboBoxModel<>(arrayBrands));
    }

    @Override
    public void updateModels() {
        String[] arrayModels = model.getArrayModels();
        jComboBoxModels.setModel(new DefaultComboBoxModel<>(arrayModels));

    }

    @Override
    public void updateCars() {

        String[] arrayCars = model.getArrayNewAuto();
        jAutoList.setModel(new DefaultComboBoxModel<>(arrayCars));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jAutoList;
    private javax.swing.JButton jBtnSelectCity;
    private javax.swing.JButton jBtnStopSubmit;
    private javax.swing.JButton jBtnSubmit;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxBrands;
    private javax.swing.JComboBox<String> jComboBoxModels;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldMaxPrice;
    private javax.swing.JTextField jTextFieldMaxYear;
    private javax.swing.JTextField jTextFieldMinPrice;
    private javax.swing.JTextField jTextFieldMinYear;
    private javax.swing.JLabel jTextViewCity;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
